export {
  createCommunityMcpServer,
  createMcpHandler,
  getOAuthProtectedResourceMetadataUrl,
  type CommunityMcpServerOptions,
  type McpLogger,
} from './server';

export {
  registerTools,
  requireScope,
  requireUserId,
  searchPostsSchema,
  getUserProfileSchema,
  listLeaderboardsSchema,
  summarizeThreadSchema,
  // community:write
  createPostSchema,
  updatePostSchema,
  deletePostSchema,
  createCommentSchema,
  updateCommentSchema,
  deleteCommentSchema,
  acceptSolutionSchema,
  toggleReactionSchema,
  toggleBookmarkSchema,
  followUserSchema,
  unfollowUserSchema,
  joinCircleSchema,
  leaveCircleSchema,
  // community:admin
  adminListUsersSchema,
  adminGetUserSchema,
  adminSetUserRoleSchema,
  adminDeleteUserSchema,
  adminCreateGroupSchema,
  adminUpdateGroupSchema,
  adminDeleteGroupSchema,
  adminUpdateSettingsSchema,
  adminAwardPointsSchema,
  adminCreateBadgeSchema,
  adminAwardBadgeSchema,
  adminCreateWatchedPhraseSchema,
  adminDeleteWatchedPhraseSchema,
  adminResolveFlagSchema,
  adminDeleteFlagSchema,
  adminListAuditLogsSchema,
  adminRevokeMcpClientSchema,
  type McpToolServices,
  type McpContext,
  type SearchPostsInput,
  type GetUserProfileInput,
  type ListLeaderboardsInput,
  type SummarizeThreadInput,
  type CreatePostInput,
  type UpdatePostInput,
  type DeletePostInput,
  type CreateCommentInput,
  type UpdateCommentInput,
  type DeleteCommentInput,
  type AcceptSolutionInput,
  type ToggleReactionInput,
  type ToggleBookmarkInput,
  type FollowUserInput,
  type UnfollowUserInput,
  type JoinCircleInput,
  type LeaveCircleInput,
  type AdminListUsersInput,
  type AdminGetUserInput,
  type AdminSetUserRoleInput,
  type AdminDeleteUserInput,
  type AdminCreateGroupInput,
  type AdminUpdateGroupInput,
  type AdminDeleteGroupInput,
  type AdminUpdateSettingsInput,
  type AdminAwardPointsInput,
  type AdminCreateBadgeInput,
  type AdminAwardBadgeInput,
  type AdminCreateWatchedPhraseInput,
  type AdminDeleteWatchedPhraseInput,
  type AdminResolveFlagInput,
  type AdminDeleteFlagInput,
  type AdminListAuditLogsInput,
  type AdminRevokeMcpClientInput,
} from './tools';

export {
  registerResources,
  type McpResourceServices,
} from './resources';

export {
  verifyMcpOAuthToken,
  REQUIRED_READ_SCOPE,
  REQUIRED_WRITE_SCOPE,
  REQUIRED_ADMIN_SCOPE,
  TOKEN_ISSUER,
  TOKEN_AUDIENCE,
  type VerifiedMcpToken,
  type McpClientInfo,
  type LookupMcpClient,
  type McpAuthOptions,
} from './auth';
